# general settings
name: Nafnet_mipi_option.yml
model_type: DeflareModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Flare7K
    type: Image_Pair_Loader
#    type: Flare_Pair_Loader
#    image_path: dataset/Flickr24K
    dataroot_gt: dataset/mipi_traindata/train_gt_2k
    dataroot_lq: dataset/mipi_traindata/train_input_2k
    gt_size: 512
#    scattering_dict:
#      Flare7K_scattering: dataset/Flare7k/Scattering_Flare/Compound_Flare
#    reflective_dict: {}
    transform_base:
      img_size: 512
    transform_flare:
      scale_min: 0.8
      scale_max: 1.5
      translate: 300
      shear: 20
    mask_type: ~
    
    # data loader
    
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Validation data is not provided in our Flare7K dataset, you can generate by yourself
  val:
    name: flare_test
    type: Image_Pair_Loader
    dataroot_gt: dataset/mipi_valdata/val_input_2k_bicbic
    dataroot_lq: dataset/mipi_valdata/val_input_2k_bicbic
    gt_size: 512

# network structures
network_g:
  type: Nafnet
#  img_size: 512
#  img_ch: 3
#  output_ch: 6
#  multi_stage: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [600000]
    gamma: 0.5

  ema_decay: 0
  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L_Abs_pure
    loss_weight: 0.5

  perceptual:
    type: L_percepture
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
